version: "3.8"

services:
  backend:
    build: ./url-shortener-backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    env_file:
      - ./url-shortener-backend/.env
    networks:
      - app-network

  frontend:
    build: ./url-shortener-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: myuser
      POSTGRES_DB: myuser
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  postgres_data:
